In [26]:
import pandas as pd
import numpy as np
import tensorflow as tf
from datetime import datetime, timedelta
import plotly.express as px
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error,mean_squared_error
from sklearn.preprocessing import StandardScaler
import os

## Data Preprocessing

In [ ]:
#     Check empty files, if there is, can't concat
#     if os.stat(file_path).st_size==0:
#         print(filename)

In [174]:
base_path = r"C:\Users\wmkoa\Downloads\Fund data\AIA"

dir_lists = os.listdir(base_path)
df_list_all = []
for i in range(1,len(dir_lists)+1):
    dir_link = os.path.join(base_path, str(i))
    dir_lists = os.listdir(dir_link)
    df_list_fund = []
    for filename in dir_lists:
        file_path = os.path.join(dir_link, filename)
        df = pd.read_csv(file_path,names=['Date', 'Price'],index_col=[0],parse_dates=[0])
        df['Price'] = df['Price'].str.replace("\t","")
        df.rename(columns={'Price': df['Price'][0] +'_Price'}, inplace=True)
        df = df[pd.to_numeric(df.iloc[:,0], errors='coerce').notnull()]
        df_list_fund.append(df)
    df_list_all.append(pd.concat(df_list_fund).sort_index())

# for item in df_list_all:
#     item.reset_index(inplace=True)
#     #item.reset_index(drop=True, inplace=True)
# #     df = pd.merge(df, item, on='Date', how='outer')
# df = pd.concat(df_list_all, axis=1)

In [180]:
# Export indivdual fund price to csv
for i in range(len(df_list_all)):
    df_list_all[i].to_csv(os.path.join(base_path,(df_list_all[i].columns[0] + '.csv')), encoding='utf_8_sig')

In [192]:
for item in df_list_all:
    print(item.columns[0])

65歲後基金_Price
大中華股票基金_Price
中港動態資產配置基金_Price
中港基金_Price
日本股票基金_Price
北美股票基金_Price
全球基金_Price
均衡組合_Price
亞洲股票基金_Price
亞洲債券基金_Price
亞歐基金_Price
美洲基金_Price
香港股票基金_Price
核心累積基金_Price
基金經理精選退休基金_Price
強積金保守基金_Price
富達增長基金_Price
富達穩定資本基金_Price
富達穩定增長基金_Price
綠色退休基金_Price
增長組合_Price
歐洲股票基金_Price
環球債券基金_Price
穩定資本組合_Price

In [191]:
# Export combined fund price to csv
df = pd.concat(df_list_all, axis=1).sort_index()
df.to_csv(os.path.join(base_path,'combined_fund_prices.csv'), encoding='utf_8_sig')

In [302]:
# Add fund type
copyOfDf_list_all = df_list_all.copy()
fund_type_list = pd.read_excel(r"C:\Users\wmkoa\Downloads\Fund data\Mpf data (uncleared).xlsx", "AIA_fund_type",header=None,names=['Type', 'Fund'])
for i in range(len(copyOfDf_list_all)):
    fundname_1 = df_list_all[i].columns[0].split('_')[0].strip()
    copyOfDf_list_all[i][fundname_1 + '_Fund_type'] = fund_type_list.loc[fund_type_list['Fund'] == fundname_1].iloc[0]['Type']

In [303]:
copyOfDf_list_all[0]

           65歲後基金_Price   65歲後基金_Fund_type
Date
2017/04/01          1.0  Mixed Asset Funds
2017/04/02          1.0  Mixed Asset Funds
2017/04/03          1.0  Mixed Asset Funds
2017/04/04          1.0  Mixed Asset Funds
2017/04/05       0.9999  Mixed Asset Funds
...                 ...                ...
2020/10/18       1.1825  Mixed Asset Funds
2020/10/19       1.1797  Mixed Asset Funds
2020/10/20       1.1788  Mixed Asset Funds
2020/10/21       1.1769  Mixed Asset Funds
2020/10/22       1.1751  Mixed Asset Funds

[1301 rows x 2 columns]

In [292]:
# df_list_all[0] = df_list_all[0].drop('OMG',1)
df_list_all[0]

           65歲後基金_Price         65歲後基金_Fund_type
Date
2017/04/01          1.0  24    Mixed Asset Funds
2017/04/02          1.0  24    Mixed Asset Funds
2017/04/03          1.0  24    Mixed Asset Funds
2017/04/04          1.0  24    Mixed Asset Funds
2017/04/05       0.9999  24    Mixed Asset Funds
...                 ...                      ...
2020/10/18       1.1825  24    Mixed Asset Funds
2020/10/19       1.1797  24    Mixed Asset Funds
2020/10/20       1.1788  24    Mixed Asset Funds
2020/10/21       1.1769  24    Mixed Asset Funds
2020/10/22       1.1751  24    Mixed Asset Funds

[1301 rows x 2 columns]